### PR TITLE
Fix list parsing in CLI option.

### PR DESCRIPTION
**Pull request by marikomedlock**
Fix list parsing, change from comma-separated option to a space-separated positional parameter.

### CODE REVIEW

**Review by chenchals — CHANGES_REQUESTED** [review]
A simple adding `split` to the options command seems to fix the issue 
For `EntityNames`
```
public class EntityNames {
  @CommandLine.Option(
      names = "--names",
      split = ",",
      description = "Entity name(s). Comma-separated list if more than one.")
  public List<String> names;
```
Ditto for `EntityGroupNames`
```
public class EntityGroupNames {
  @CommandLine.Option(
      names = "--names",
      split = ",",
      description = "Entity group name(s). Comma-separated list if more than one.")
  public List<String> names;
```

**Comment by marikomedlock** [comment]
> A simple adding `split` to the option command seems to fix the issue For `EntityNames`
> 
> ```
> public class EntityNames {
>   @CommandLine.Option(
>       names = "--names",
>       split = ",",
>       description = "Entity name(s). Comma-separated list if more than one.")
>   public List<String> names;
> ```
> 
> Ditto for `EntityGroupNames`
> 
> ```
> public class EntityGroupNames {
>   @CommandLine.Option(
>       names = "--names",
>       split = ",",
>       description = "Entity group name(s). Comma-separated list if more than one.")
>   public List<String> names;
> ```

Oh that's much better, thanks. I'll give it a try

**Review by chenchals — APPROVED** [review]
thanks! what are .adoc files?

**Comment by marikomedlock** [comment]
> thanks! what are .adoc files?

They're like markdown, just a different format for writing documentation. These adoc files are generated by the CLI library we're using for the indexer.

**Pull request merged**
