### PR TITLE
Handle invalid regexps by treating them as plain strings

### PR DESCRIPTION
**Pull request by tjennison-google**

### CODE REVIEW

**Review by marikomedlock — COMMENTED** [review]
Are these regexps entered by the user in the text search bar?

**Comment by tjennison-google** [comment]
> Are these regexps entered by the user in the text search bar?

Yes. The backend still returns an error for the invalid regex but now that's just in the search results instead of taking over the entire page because of the JS exception.

**Comment by marikomedlock** [comment]
> > Are these regexps entered by the user in the text search bar?
> 
> Yes. The backend still returns an error for the invalid regex but now that's just in the search results instead of taking over the entire page because of the JS exception.

But the backend isn't handling regexps at all -- is it? At least, I'm not handling them in the query engine.

**Comment by tjennison-google** [comment]
> > > Are these regexps entered by the user in the text search bar?
> > 
> > 
> > Yes. The backend still returns an error for the invalid regex but now that's just in the search results instead of taking over the entire page because of the JS exception.
> 
> But the backend isn't handling regexps at all -- is it? At least, I'm not handling them in the query engine.

Looks like it's coming from BQ:

...
  "message": "Cannot parse regular expression: missing ]: [C",                                                                                                   
  "status": "INVALID_ARGUMENT"                                                                                                                                   
},                                                                                                                                                               
                                                                                                                                                                 
com.google.cloud.bigquery.BigQueryException: Cannot parse regular expression: missing ]: [C                                                                      
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:114)                                                                  
        at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.getQueryResults(HttpBigQueryRpc.java:702)                                                            
        at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1441)                                                                                
        at com.google.cloud.bigquery.BigQueryImpl$36.call(BigQueryImpl.java:1436)                                                                                
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)                                                            
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)                                                                        
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)                                                             
        at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1435)                                                                        
        at com.google.cloud.bigquery.BigQueryImpl.getQueryResults(BigQueryImpl.java:1419)                                                                        
        at com.google.cloud.bigquery.Job$1.call(Job.java:343)                                                                                                    
        at com.google.cloud.bigquery.Job$1.call(Job.java:340)                                                                                                    
        at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103)                                                            
        at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86)                                                                        
        at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49)                                                             
        at com.google.cloud.bigquery.Job.waitForQueryResults(Job.java:339)                                                                                       
        at com.google.cloud.bigquery.Job.getQueryResults(Job.java:295)                                                                                           
        at bio.terra.tanagra.utils.GoogleBigQuery.lambda$queryBigQuery$4(GoogleBigQuery.java:220)                                                                
        at bio.terra.tanagra.utils.HttpUtils.pollWithRetries(HttpUtils.java:149)                                                                                 
        at bio.terra.tanagra.utils.HttpUtils.callWithRetries(HttpUtils.java:83)                                                                                  
        at bio.terra.tanagra.utils.GoogleBigQuery.lambda$callWithRetries$7(GoogleBigQuery.java:305)                                                              
        at bio.terra.tanagra.utils.GoogleBigQuery.handleClientExceptions(GoogleBigQuery.java:324)                                                                
        at bio.terra.tanagra.utils.GoogleBigQuery.callWithRetries(GoogleBigQuery.java:303)                                                                       
        at bio.terra.tanagra.utils.GoogleBigQuery.queryBigQuery(GoogleBigQuery.java:219)                                                                         
        at bio.terra.tanagra.query.bigquery.BigQueryExecutor.execute(BigQueryExecutor.java:44)                                                                   
        at bio.terra.tanagra.service.query.UnderlayService.listEntityInstances(UnderlayService.java:101)                                                         
        at bio.terra.tanagra.app.controller.UnderlaysApiController.listInstances(UnderlaysApiController.java:96)

**Comment by marikomedlock** [comment]
Per offline discussion. The backend does not currently support regexps, though we plan to add more advanced text search in the future. This PR makes sure we don't get an error page if the user enters a regex character.

**Review by marikomedlock — APPROVED** [review]

**Pull request merged**
