### PR TITLE
Add support for adding criteria from cohorts and feature sets

### PR DESCRIPTION
**Pull request by tjennison-google**

### CODE REVIEW

**Review by marikomedlock — COMMENTED** [review]
Just to clarify, is this to allow:
 - creating a new feature set from a single criteria group in a cohort
 - creating a new cohort from a single criteria in a data feature set

Screenshot maybe to help me follow the intended change?

**Comment by tjennison-google** [comment]
> Just to clarify, is this to allow:
> 
> * creating a new feature set from a single criteria group in a cohort
> * creating a new cohort from a single criteria in a data feature set
> 
> Screenshot maybe to help me follow the intended change?

It adds an option to add criteria to a cohort from a feature set and vice-versa.

image
image
image

**Comment by marikomedlock** [comment]
> It adds an option to add criteria to a cohort from a feature set and vice-versa.

Gotcha, okay so code looks like it adds all (valid) criteria, not allows user to select one, right?

**Review by marikomedlock — APPROVED** [review]

**Comment by tjennison-google** [comment]
> > It adds an option to add criteria to a cohort from a feature set and vice-versa.
> 
> Gotcha, okay so code looks like it adds all (valid) criteria, not allows user to select one, right?

Right

**Pull request merged**
